export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAIL = "FETCH_CURRENT_USER_FAIL";
export const FETCH_CURRENT_USER_START = "FETCH_CURRENT_USER_START";
