export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAIL = "FETCH_CURRENT_USER_FAIL";
export const FETCH_CURRENT_USER_START = "FETCH_CURRENT_USER_START";

export const FETCH_PLAYLIST_START = "FETCH_PLAYLIST_START";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
export const FETCH_PLAYLIST_FAIL = "FETCH_PLAYLIST_FAIL";

export const ADD_DEVICE_ID = "ADD_DEVICE_ID";
export const SET_PROGRESS = "SET_PROGRESS";
export const PLAY = "PLAY";
export const PAUSE = "PAUSE";
export const UPDATE_PLAYER_START = "UPDATE_PLAYER_START";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_FAIL = "UPDATE_PLAYER_FAIL";
